first-commit
FausT-VX/sprint-10-final-project pull request #1
Opened 2024-06-23 11:36 UTC by FausT-VX

2024-06-23 12:16 UTC, dirtymew requested changes
Привет Антон

хорошая работа - но немного нужно доделать

2024-06-23 12:16 UTC, dirtymew commented on precode.sh
> +mkdir task && mkdir task/dir{1..3} && mkdir task/dir3/dir4
можно  еще так mkdir -p task/dir1 task/dir2 task/dir3/dir4

2024-06-23 12:16 UTC, dirtymew commented on precode.sh
> +cp -r -T dir2 dir3/dir4/ # или cp dir2/* dir3/dir4/
-T опция не везде поддерживаемая для cp

2024-06-23 12:16 UTC, dirtymew commented on precode.sh
> +NAME='Всем студентам'
тут неверно нужно создать переменную окружения а не просто переменную

2024-06-23 12:16 UTC, dirtymew commented on precode.sh
> +dir2/hello.sh "$NAME"
тут не сделано - "вывод скрипта должен дописаться в файл task/dir1/summary.txt"

2024-06-23 13:10 UTC, FausT-VX commented on precode.sh
> +cp -r -T dir2 dir3/dir4/ # или cp dir2/* dir3/dir4/
Я же в в коментах написал # или cp dir2/* dir3/dir4/
А так сделал чтобы соответствовало пройденной теории, тяжело подгонять под требуемое решение, когда вариантов много :)

2024-06-23 13:16 UTC, FausT-VX commented on precode.sh
> +NAME='Всем студентам'
> тут неверно нужно создать переменную окружения а не просто переменную
Про переменные окружения в теории не было ничего, но зато в полезных советах к заданию:
![image](https://github.com/FausT-VX/sprint-10-final-project/assets/112948308/8be80bfc-ef5f-4640-bdcc-5d6f33a1dd04)
 
Локальная переменная окружения создаётся простым присваиванием. Она будет действительна только для текущей сессии:
VAR='Значение'

2024-06-23 13:17 UTC, FausT-VX commented on precode.sh
> +mkdir task && mkdir task/dir{1..3} && mkdir task/dir3/dir4
спасибо за совет!

2024-06-23 13:19 UTC, FausT-VX commented on precode.sh
> +dir2/hello.sh "$NAME"
> тут не сделано - "вывод скрипта должен дописаться в файл task/dir1/summary.txt"

Исправил

2024-06-23 19:53 UTC, dirtymew requested changes
Антон

нужно еще доделать

2024-06-23 19:53 UTC, dirtymew commented on precode.sh
> +NAME='Всем студентам'
тут в задание не про локальную переменную идет речь
`# определяем переменную окружения NAME со значением "Всем студентам"`

переменные окружения задаются командой export

2024-06-24 09:01 UTC, dirtymew approved these changes
Антон

все супер - зачет

2024-12-16 09:10 UTC, merged